# Generated by Django 2.1.3 on 2018-11-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=12)),
            ],
        ),
    ]
