# Generated by Django 2.1.3 on 2018-11-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsmodel',
            name='first_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='accountsmodel',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accountsmodel',
            name='last_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
