# Generated by Django 2.1.3 on 2018-11-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181129_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsmodel',
            name='prof_pic',
            field=models.ImageField(blank=True, upload_to='insta_pics/profile_pics'),
        ),
    ]
