# Generated by Django 2.1.3 on 2018-11-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountsmodel_prof_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsmodel',
            name='prof_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
