# Generated by Django 2.1.4 on 2018-12-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='follow',
        ),
    ]
