# Generated by Django 2.1.3 on 2018-12-03 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181129_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AccountsModel')),
            ],
        ),
    ]
