# Generated by Django 2.1.4 on 2018-12-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_followers_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='following',
            field=models.IntegerField(default=0),
        ),
    ]
