# Generated by Django 2.1.3 on 2018-12-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_followersmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followersmodel',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='accountsmodel',
            name='prof_pic',
            field=models.ImageField(blank=True, null=True, upload_to='prof_pic'),
        ),
    ]
