# Generated by Django 2.1.3 on 2018-11-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedmodel',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedmodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
