# Generated by Django 2.1.4 on 2018-12-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likesuser',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
