# Generated by Django 2.1.4 on 2018-12-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_following'),
        ('feed', '0002_likesuser_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeds',
            name='liked',
            field=models.ManyToManyField(to='feed.LikesUser'),
        ),
        migrations.AddField(
            model_name='feeds',
            name='liker',
            field=models.ManyToManyField(to='accounts.Account'),
        ),
    ]
