# Generated by Django 2.1.4 on 2018-12-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_remove_likesuser_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='archived_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feeds',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
