# Generated by Django 2.1.4 on 2018-12-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20181226_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='liked',
            field=models.ManyToManyField(blank=True, to='feed.LikesUser'),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='liker',
            field=models.ManyToManyField(blank=True, to='accounts.Account'),
        ),
    ]
