# Generated by Django 2.1.4 on 2018-12-26 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_likesuser_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likesuser',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.Feeds'),
        ),
    ]
