# Generated by Django 2.1.3 on 2018-12-04 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_auto_20181203_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicturesUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='insta_pics')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AccountsModel')),
            ],
        ),
    ]
